Rename dispatch to send for consistency with TCA
toggl/komposable-architecture pull request #27
Opened 2022-02-25 17:11 UTC by jonekdahl

## Summary
As discussed in #23, using `send` instead of `dispatch` would be beneficial for individuals and teams that have previous experience with TCA (The Composable Architecture). This PR changes the name to `send`, deprecating the `dispatch` methods.

## Relationships
Closes #23

## Technical considerations
-

## Tests
Existing tests have been updated. No new tests have been added since this is just a rename that doesn't introduce any new behavior.

## Review pointers
As suggested by @semanticer, `@Deprecated` annotations were added, I hope I did them correctly.

2022-03-15 18:09 UTC, semanticer requested changes
I'm sorry for the late review and thanks again for this valuable contribution. 

Nothing seems to be broken, all the changes are correct IMO and I tested whether @Deprecation annotation works and it does 👍 

However, by searching the whole project for "dispatch" I discovered many other places we should probably fix. It's mostly in the docs, comments or tests but we should also probably rename those 
`dispatchFn: (List<Action>) -> Unit`
as well right? @toggl/androids

2022-03-27 08:38 UTC, jonekdahl commented
Hi @semanticer! Are you expecting feedback from @toggl/androids or can I go ahead and do the changes you propose?

2022-03-27 09:41 UTC, semanticer commented
> Hi @semanticer! Are you expecting feedback from @toggl/androids or can I go ahead and do the changes you propose?

Go for it, and thanks again!

2022-03-28 04:20 UTC, pdrj commented
Sorry that it's taking so long @jonekdahl 

>It's mostly in the docs, comments or tests but we should also probably rename those
dispatchFn: (List<Action>) -> Unit
as well right?

Yeah, it'd be good to have these changed as well to avoid confusion.

2022-05-05 14:02 UTC, jonekdahl commented
@semanticer Oh, go ahead!

2022-05-05 19:48 UTC, semanticer commented
Here is the continuation #30

2022-05-05 19:48 UTC, closed without merging